<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Fallible.EVA.SDK</PackageId>
		<Version>0.0.0</Version>
		<Authors>Humphrey Kganakga</Authors>
		<Description>Errors as values</Description>
		<PackageTags>roslyn analyzer generator error-handling</PackageTags>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- Include analyzer and generator DLLs in the NuGet package -->
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.6.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ErrorValues.Analyzers\ErrorValues.Analyzers.csproj" />
	  <ProjectReference Include="..\ErrorValues.CodeFixes\ErrorValues.CodeFixes.csproj" />
	  <ProjectReference Include="..\ErrorValues.Generators\ErrorValues.Generators.csproj" />
	  <ProjectReference Include="..\ErrorValues.Library\ErrorValues.Library.csproj" />
	</ItemGroup>

</Project>
