using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using EVA.Attributes;

namespace EVA.Generators;


[Generator(LanguageNames.CSharp)]
public class CodeGeneratorA : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<EnumModel?> enumModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                typeof(EVAAttribute).FullName,
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (ctx, ct) => ExtractEnumMetadata(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(enumModels, static (spc, model) =>
        {
            if (model is null) return;

            string source = Generate(model.Value);
            spc.AddSource($"R{model.Value.TargetFunctionName}.g.cs", source);
        });
    }

    public static EnumModel? ExtractEnumMetadata(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enum_symbol)
            return null;

        AttributeData error_vals_attr = context.Attributes
            .FirstOrDefault(
                attribute => 
                    attribute.AttributeClass?
                    .ToDisplayString() == typeof(EVAAttribute).FullName
            );
        
        
        string target_function_name =  error_vals_attr?
            .ConstructorArguments
            .FirstOrDefault()
            .Value?
            .ToString();

        List<VariantModel> variants = []; 

        foreach(ISymbol member in enum_symbol.GetMembers())
        {
            if (member is not IFieldSymbol field || field.IsImplicitlyDeclared)
                continue;

            AttributeData payload_attr = field.GetAttributes()
                .FirstOrDefault(attribute =>
                    attribute.AttributeClass?.IsGenericType == true &&
                    attribute.AttributeClass.ConstructedFrom.MetadataName == typeof(PayloadAttribute<>).Name &&
                    attribute.AttributeClass.ConstructedFrom.ContainingNamespace.ToDisplayString() == typeof(PayloadAttribute<>).Namespace
                );

            string payload_type = null;
            bool has_payload = false;
            bool is_happy = false;
            if(payload_attr is not null && payload_attr.AttributeClass!.TypeArguments.Length > 0)
            {
                ITypeSymbol type_arg = payload_attr.AttributeClass!.TypeArguments[0];
                bool happy_parsed = bool.TryParse(
                    payload_attr
                    .ConstructorArguments
                    .FirstOrDefault()
                    .Value?.ToString(), out bool happy);

                // Format type for global emission
                payload_type = type_arg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                has_payload = true;
                is_happy = happy_parsed ? happy : is_happy;
            }

            variants.Add(new VariantModel(field.Name, payload_type, has_payload, is_happy));
        }

        string full_enum_name = enum_symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new EnumModel(
            enum_symbol.ContainingNamespace.ToDisplayString(),
            enum_symbol.Name,
            full_enum_name,
            target_function_name,
            new EquatableArray<VariantModel>([.. variants])
        );
    }

    public readonly static string OB = "{";
    public readonly static string CB = "}";

    public static string Generate(EnumModel model)
    {
        string rawName = model.EnumName.Substring(0, model.EnumName.Length - 1);
        string structName = $"{model.EnumName.Substring(0, model.EnumName.Length - 1)}R";

        return 
        $"""
        // <auto-generated/>
        #nullable enable
        using System;
        using System.Runtime.CompilerServices;
        using System.Runtime.InteropServices;

        using {nameof(EVA)}.{nameof(EVA.Attributes)};

        namespace {model.Namespace};

        [Generation(nameof({model.FullyQualifiedEnumName}))]
        internal readonly struct {structName}<T> : {typeof(IEVA<>).GetCleanName()}<T>
        {OB}
            private readonly {model.FullyQualifiedEnumName} Tag;
            private readonly Storage _storage;
            private readonly bool _happy;

            public bool Happy {OB} get => _happy; {CB}

            internal {structName}({model.FullyQualifiedEnumName} tag, Storage storage, bool happy = false)
            {OB}
                Tag = tag;
                _storage = storage;
                _happy = happy;
            {CB}

            public static implicit operator {model.FullyQualifiedEnumName}({structName}<T> result)
                => result.Tag;

            public {rawName}Exception ToException()
            {OB}
                switch(Tag)
                {OB}
                    {GenerateCases(model)}
                {CB}
                return new {rawName}Exception();
            {CB}

            {GenerateTryAccessors(model)}

            {GenerateFactoryMethods(structName, model)}
            {GeneratePayloadMethods(model)}
            {GenerateStorageStruct(model)}
        {CB}


        [Generation(nameof({model.FullyQualifiedEnumName}))]
        internal class {rawName}Exception : Exception {OB}{CB}

        {GenerateExceptions(rawName, model)}
        """;
    }

    private static string GenerateTryAccessors(EnumModel model)
    {
        List<string> accessors = [];
        foreach (VariantModel v in model.Variants)
        {
            accessors.Add(
                $"""
                public bool Is{v.Name} => {model.FullyQualifiedEnumName}.{v.Name} == Tag;
                """
            );
        }
        return StringFormatLines(
            lines: accessors,
            prefix: "",
            line_separator: ("", new string(' ', 4)),
            postfix: ""
        );
    }

    private static string GenerateFactoryMethods(string structName, EnumModel model)
    {
        StringBuilder builder = new();
        foreach (VariantModel v in model.Variants)
        {
            if (v.HasPayload)
            {
                builder.AppendLine(
                $"""
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    internal static {structName}<T> {v.Name}({v.PayloadTypeFullyQualified} payload)
                    {OB}
                        var storage = new Storage {OB} {v.Name} = payload {CB};
                        return new {structName}<T>({model.FullyQualifiedEnumName}.{v.Name}, storage, {v.Happy.ToString().ToLower()});
                    {CB}

                """);
            }
            else
            {
                builder.AppendLine(
                $"""
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    internal static {structName}<T> {v.Name}()
                    {OB}
                        return new {structName}<T>({model.FullyQualifiedEnumName}.{v.Name}, default, {v.Happy.ToString().ToLower()});
                    {CB}

                """);
            }
        }
        return builder.ToString();
    }

    private static string GeneratePayloadMethods(EnumModel model)
    {
        StringBuilder builder = new();
        foreach (VariantModel variant in model.Variants)
        {
            if (variant.HasPayload)
            {
                builder.AppendLine(
                $"""
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    internal {variant.PayloadTypeFullyQualified} {variant.Name}()
                    {OB}
                        if(Tag == {model.FullyQualifiedEnumName}.{variant.Name})
                            return _storage.{variant.Name};
                        throw new InvalidOperationException($"{variant.Name} does not match the error value {OB}Tag{CB}");
                    {CB}

                """);
            }
        }
        return builder.ToString();
    }

    private static string GenerateStorageStruct(EnumModel model)
    {
        List<string> fields = [];
        foreach (VariantModel v in model.Variants)
        {
            if (v.HasPayload)
            {
                fields.Add($"public {v.PayloadTypeFullyQualified} {v.Name};");
            }
        }

        return 
        $"""
        [StructLayout(LayoutKind.Sequential)]
            internal struct Storage
            {OB}
                {StringFormatLines(
                    lines: fields, 
                    prefix: "", 
                    line_separator: ("", new string(' ', 8)),
                    postfix: "")}
            {CB}
        """;
    }

    private static string GenerateExceptions(string raw_name, EnumModel model)
    {
        StringBuilder str = new();
        foreach (VariantModel v in model.Variants)
        {
            if(!v.Happy)
            {
                if (v.HasPayload)
                {
                    str.Append(
                        $"""
                        [{nameof(GenerationAttribute)}(nameof({model.FullyQualifiedEnumName}))]
                        internal class {v.Name}Exception : {raw_name}Exception
                        {OB}
                            internal {v.PayloadTypeFullyQualified} Payload;
                            internal {v.Name}Exception({v.PayloadTypeFullyQualified} payload)
                            {OB}
                                Payload = payload;
                            {CB}
                        {CB}

                        """);
                    str.AppendLine("");
                }
                else
                {
                    str.Append(
                        $"""
                        [{nameof(GenerationAttribute)}(nameof({model.FullyQualifiedEnumName}))]
                        internal class {v.Name}Exception : {raw_name}Exception
                        {OB}
                    
                        {CB}

                        """);
                    str.AppendLine("");
                }
            }
        }
        return str.ToString();
    }

    private static object GenerateCases(EnumModel model)
    {
        List<string> cases = [];
        foreach(VariantModel v in model.Variants)
        {
            if(!v.Happy)
            {
                if (v.HasPayload)
                {
                    cases.Add(
                        $"""
                        case {model.FullyQualifiedEnumName}.{v.Name}: 
                        {new string(' ', 16)}return new {v.Name}Exception(_storage.{v.Name});
                        """
                    );
                }
                else
                {
                    cases.Add(
                        $"""
                        case {model.FullyQualifiedEnumName}.{v.Name}: 
                        {new string(' ', 16)}return new {v.Name}Exception();
                        """
                    );
                }               
            }
        }
        return StringFormatLines(
            lines: cases,
            prefix: "",
            line_separator: ("", new string(' ', 12)),
            postfix: ""
        );
    }

    private static string StringFormatLines(List<string> lines, string prefix, (string end, string start) line_separator, string postfix)
    {
        StringBuilder sb = new();
        for (int i = 0; i < lines.Count; i++)
        {
            if(i == 0)
                sb.Append(prefix);
            else
                sb.Append(line_separator.start);
            string line = lines[i];
            sb.Append(line);
            if(i < lines.Count - 1)
            {
                sb.Append(line_separator.end);
                sb.Append('\n');
            }
        }
        sb.Append(postfix);

        return sb.ToString();
    }
}

public record struct VariantModel(
    string Name,
    string PayloadTypeFullyQualified,
    bool HasPayload,
    bool Happy);

public record struct EnumModel(
    string Namespace,
    string EnumName,
    string FullyQualifiedEnumName,
    string TargetFunctionName,
    EquatableArray<VariantModel> Variants);

public readonly struct EquatableArray<T>(T[] array) : IEquatable<EquatableArray<T>>, IEnumerable<T>
    where T : IEquatable<T>
{
    private readonly T[] _array = array;

    public ReadOnlySpan<T> AsSpan() 
        => _array is null 
        ? ReadOnlySpan<T>.Empty 
        : _array.AsSpan();

    public bool Equals(EquatableArray<T> other) 
        => AsSpan().SequenceEqual(other.AsSpan());

    public override bool Equals(object obj) 
        => obj is EquatableArray<T> other && Equals(other);

    public override int GetHashCode()
    {
        if (_array is null) 
            return 0;
        HashCode hash = new();
        foreach (var item in _array) 
            hash.Add(item);
        return hash.ToHashCode();
    }

    public IEnumerator<T> GetEnumerator() 
        => ((IEnumerable<T>)(_array ?? [])).GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() 
        => GetEnumerator();
}