// <auto-generated/>
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace ErrorValues.ScratchSpace;

internal readonly ref struct RMyFun<T>
{
    internal readonly global::ErrorValues.ScratchSpace.Program.MyFunErrors Tag;
    private readonly Storage _storage;

    internal RMyFun(global::ErrorValues.ScratchSpace.Program.MyFunErrors tag, Storage storage)
    {
        Tag = tag;
        _storage = storage;
    }

    public static implicit operator global::ErrorValues.ScratchSpace.Program.MyFunErrors(RMyFun<T> result)
        => result.Tag;

    public bool IsNone
    => global::ErrorValues.ScratchSpace.Program.MyFunErrors.None == Tag;
    public bool IsOne
        => global::ErrorValues.ScratchSpace.Program.MyFunErrors.One == Tag;
    public bool IsTwo
        => global::ErrorValues.ScratchSpace.Program.MyFunErrors.Two == Tag;
    public bool IsThree
        => global::ErrorValues.ScratchSpace.Program.MyFunErrors.Three == Tag;


    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static RMyFun<T> None(int payload)
    {
        var storage = new Storage { None = payload };
        return new RMyFun<T>(global::ErrorValues.ScratchSpace.Program.MyFunErrors.None, storage);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static RMyFun<T> One(byte[] payload)
    {
        var storage = new Storage { One = payload };
        return new RMyFun<T>(global::ErrorValues.ScratchSpace.Program.MyFunErrors.One, storage);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static RMyFun<T> Two(global::System.IO.FileAccess payload)
    {
        var storage = new Storage { Two = payload };
        return new RMyFun<T>(global::ErrorValues.ScratchSpace.Program.MyFunErrors.Two, storage);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static RMyFun<T> Three()
    {
        return new RMyFun<T>(global::ErrorValues.ScratchSpace.Program.MyFunErrors.Three, default);
    }


    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal int None()
    {
        if (Tag == global::ErrorValues.ScratchSpace.Program.MyFunErrors.None)
            return Unsafe.As<Storage, int>(ref Unsafe.AsRef(in _storage));
        throw new InvalidOperationException($"None does not match the error value {Tag}");
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal byte[] One()
    {
        if (Tag == global::ErrorValues.ScratchSpace.Program.MyFunErrors.One)
            return Unsafe.As<Storage, byte[]>(ref Unsafe.AsRef(in _storage));
        throw new InvalidOperationException($"One does not match the error value {Tag}");
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal global::System.IO.FileAccess Two()
    {
        if (Tag == global::ErrorValues.ScratchSpace.Program.MyFunErrors.Two)
            return Unsafe.As<Storage, global::System.IO.FileAccess>(ref Unsafe.AsRef(in _storage));
        throw new InvalidOperationException($"Two does not match the error value {Tag}");
    }


    [StructLayout(LayoutKind.Sequential)]
    internal ref struct Storage
    {
        public int None;
        public byte[] One;
        public global::System.IO.FileAccess Two;
    }
}